### ISSUE TITLE
Nitpicking about bookmarks in the documentation

### ISSUE THREAD

**Issue by Rimole** [bdtc/metalogox#3]
metalogox v1.02—2024/01/12

bookmarks:
...
- Change History and Index
- ChangeHistory
- Index
   + A
   + B
...

I think that 
- either there should be no combined entry "Change History and Index" but only "Change History" and "Index"
- or "Change History" and "Index" should be subentries to "Change History and Index", not entries at the same level.

**Comment by bdtc** [comment]
True.  Will do.  Also have to fix this in tocdata and dtxdescribe packages as well.  Thanks.

**Comment by bdtc** [comment]
Done in v1.03.
