### ISSUE TITLE
Interaction with hologo package

### ISSUE THREAD

**Issue by chupinmaxime** [bdtc/metalogox#5]
Thanks for this package, it is a great idea. 
[hologo](https://www.ctan.org/pkg/hologo) implements a very good mechanism for composing *TeX logos. Is that possible to interact with it and to adapt the different logos using both hologo and metalogox?

**Comment by bdtc** [comment]
Good idea.  I have added it to v1.04.

I'll wait a bit and see if anything else comes up before releasing.

**Comment by bdtc** [comment]
v1.04 now adds support for the LaTeX hologo and hvlogos packages.
